### ISSUE TITLE
Support for ops-files in bbl-up

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/cf-deployment-concourse-tasks#17]
Hey,

It would be lovely to support bosh ops-files in the bbl-up task. We specifically are interested in this for the `credhub` [opsfile](https://github.com/cloudfoundry/bosh-deployment/blob/master/credhub.yml).

One side-effect of this is that `vars-store` becomes optional for the other tasks. As far as I know, concourse does not allow optional inputs, so this might be in support of the discussion happening in #13.

No good suggestions on how to take in the list of ops-files either, as that answer overlaps a bit with https://github.com/cloudfoundry/cf-deployment-concourse-tasks/issues/2

**Comment by dsabeti** [comment]
Hey @ljfranklin. I think this makes sense. The only holding me back from prioritizing a story for this is to finally investigate the bosh-deployment resource.

**Comment by dsabeti** [comment]
Hey @ljfranklin, after thinking about this a bit more, I realized that this gets a bit more complicated. We can definitely add the functionality to provide ops-files to `bbl up`, but as far as handling Credhub, it's more work. How urgent is it for the CAPI team to start working with Credhub?

As for allowing `bbl up` to take an ops-file, I'm thinking this might be the interface we're shooting for:
```
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v2.1.0

inputs:
- name: cf-deployment-concourse-tasks
- name: bbl-state
- name: ops-files          # New input

outputs:
- name: updated-bbl-state

run:
  path: cf-deployment-concourse-tasks/bbl-up/task

params:
  BBL_AWS_ACCESS_KEY_ID:
  BBL_AWS_SECRET_ACCESS_KEY:
  BBL_AWS_REGION:
  BBL_GCP_SERVICE_ACCOUNT_KEY:
  BBL_GCP_PROJECT_ID:
  BBL_GCP_ZONE:
  BBL_GCP_REGION:
  BBL_STATE_DIR:
  BBL_IAAS:
  BBL_LB_CERT:
  BBL_LB_KEY:
  LB_DOMAIN:
  BBL_ENV_NAME:

  BBL_OPS_FILES:          # New param
```

We'll probably have to bump the major version of the repo.
