### ISSUE TITLE
Setting the committer name and email

### ISSUE THREAD

**Issue by utricularian** [cloudfoundry/cf-deployment-concourse-tasks#19]
We want to use the tasks in this repo, but we'd also like to set the commits with our own teams email address and bot username. Are there any plans to parameterize git config such as:
https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/7c86b2a790c68d326be3592969f240d207e58342/shared-functions#L26

cc @zankich

**Comment by dsabeti** [comment]
@utricularian That seems like a very reasonable feature request. I'm going to co-opt this issue and the corresponding tracker story to allow that to be parameterized.

I think the update to the interface would be:
```
...
params:
  BBL_STATE_DIR:
  MANIFEST_FILE: cf-deployment.yml
  OPS_FILES:
  SYSTEM_DOMAIN:
  VARS_STORE_FILE: deployment-vars.yml
  REGENERATE_VARS_STORE: false

  # New param
  GIT_COMMIT_EMAIL: cf-release-integration@pivotal.io
```

It maintains backwards compatibility and gives a default, but pretty easily allows the user to override it.
