### ISSUE TITLE
Feature Request: support ops-files from multiple repositories in bosh-deploy

### ISSUE THREAD

**Issue by aashah** [cloudfoundry/cf-deployment-concourse-tasks#2]
Not sure whether concourse will fully be able to support this, but it'd be nice to allow teams to have their own ops files. Currently, in order to write our own, we had to "vendor" the ops-files in `cf-deployment`.

**Comment by dsabeti** [comment]
@aashah Yeah, this one is hard, because concourse doesn't support making tasks with a variable number of arguments.

One thing we talked about shipping was a task that copies ops files into a centralized location. So imagine that you had the `cf-deployment` repo and a `xena-env` repo that had custom ops files in a directory called `custom-ops-files`. You could configure your job like this:
```
- name: deploy
  plan:
  - get: cf-deployment
  - get: xena-env
  - task: centralize-ops-files
    file: cf-deployment-concourse-tasks/centralize-ops-files/task.yml
    input_mapping:
      input-ops-repo: cf-deployment
      target-ops-repo: xena-env
    output_mapping:
      updated-target-ops-repo: updated-xena-env
    params:
      INPUT_OPS_FILE_PATH: operations/gcp.yml
      TARGET_OPS_FILE_PATH: custom-ops-files
  - task: bosh-deploy
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      ops-files: updated-xena-env
    params:
      OPS_FILES: "custom-ops-files/gcp.yml custom-ops-files/xena-specific-ops-file.yml"
```

The task would be REALLY simple (probably just a `cp` from one directory to another), so you could implement this yourself.Also, you'd have to run this task once for each ops file that you wanted to centralize. This isn't a great solution. Unfortunately, I'm not sure I can think of anything better.

Let me know if this would satisfy your use case. I'll also wait to see if other teams need something like this as well. In the meantime, I can try to poke the concourse team for help.
