### ISSUE TITLE
cf tail command not found in docker image.

### ISSUE THREAD

**Issue by arthomps** [cloudfoundry/cf-deployment-concourse-tasks#79]
Our CATs tests started failing recently with the error:

`'tail' is not a registered command. See 'cf help -a'`

After some tracing, what I believe has happened is that CATs set the use-log-cache option to default to true whereas it used to be false by default.  

https://github.com/cloudfoundry/cf-acceptance-tests/commit/63c12afa94037a3e6a9e4a13495a0a0e6d05b3a8

This may be a reasonable change.  But for users who are using the docker image defined in cf-deployment-concourse-tasks, it seems to be missing the appropriate command.  Is it possible to get https://github.com/cloudfoundry/log-cache-cli installed in the cf-deployment-concrouse-tasks docker image?

As a work around for anybody else running into this, you can turn off the use-log-cache in your cats config and the old behaviour will be restored.  at least up until cf 4.4, I haven't checked past that.

**Comment by ishustava** [comment]
Hey @arthomps 

`log-cache-cli` was added to the docker image about 7 months ago with this commit da91fc5f88d3a279236cd5cdfa0877ed900b921e. This corresponds to `cf-deployment-concourse-tasks` `v6.3` or higher. 

Which version are you using?

As a workaround, if you are on an earlier version, you can override the docker image version in your pipeline following these steps:
1. Add docker image resource (`v5.5.0` or higher will have `log-cache-cli`)
    ```
    resources:
    - name: cf-deployment-concourse-tasks-docker-image-v5-5-0
       type: docker-image
       source:
          repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
          tag: v5.5.0
     ```
1. Override image for each task that needs it:
    ```
    jobs:
    - name: run-cats
      plan:
      - get: cf-deployment-concourse-tasks-docker-image-v5-5-0
       ...  
       - task: run-cats
          image: cf-deployment-concourse-tasks-docker-image-v5-5-0
          file: cf-deployment-concourse-tasks/run-cats/task.yml
    ```
